### ISSUE TITLE
DBus volume get/set issue

### ISSUE THREAD

**Issue by avalak** [kernelhcy/DeaDBeeF-MPRIS-plugin#12]
According to mpris2 [specification](http://specifications.freedesktop.org/mpris-spec/latest/Player_Interface.html#Simple-Type:Volume) "Volume" value should be between 0.0 and 1.0, not 0.0 and 100.0

fix:
mpris_v2.c:328
<`ret =  g_variant_new("(d)" , volume / ( - min_vol) * 100);`
>`ret =  g_variant_new("(d)" , volume / ( - min_vol));`

mpris_v2.c:393
<`float vol_f = 50 - ((float)volume / 100.0 * 50.0);`
>`float vol_f = 50 - ((float)volume * 50.0);`

**Comment by Serranya** [comment]
If you only need MPRISv2 and an dependency on glibc >= 2.32 does not bother you, you can take a look at my version of this Plugin https://github.com/Serranya/deadbeef-mpris2-plugin
