### ISSUE TITLE
关于安装步骤

### ISSUE THREAD

**Issue by roverway** [kernelhcy/DeaDBeeF-MPRIS-plugin#6]
不懂c，不知道怎么安装？详细的步骤是？
我想尝试写一个arch的PKGBUILD。aur中现有的deadbeef的mpris插件似乎功能不是很完备。

**Comment by kernelhcy** [comment]
$./autogen.sh
$./configure
$make
#make install

## 

北京清软时代科技有限公司   黄丛宇
北京市海淀区五道口华清嘉园6号楼1604室
不抛弃，不放弃。愿赌服输，虽败犹荣。

Sent with Sparrow (http://www.sparrowmailapp.com/?sig)
